### ISSUE TITLE
Google reCaptch

### ISSUE THREAD

**Issue by Dheerajmadhukar** [justcatthefish/ctfplatform#3]
Captcha is not working .... Do remove the same or manage it from one location !

**Comment by patryk4815** [comment]
@Dheerajmadhukar it probably needs to be replaced manually here:
https://github.com/justcatthefish/ctfplatform/blob/master/frontend/src/consts/index.ts#L9

**Comment by Dheerajmadhukar** [comment]
I want to remove captcha from register & login page !!!
